### ISSUE TITLE
Spring Security Architecture

### ISSUE THREAD

**Issue by WladimirHSJW** [tridungng/SpringBootJWT#1]
Hab ich gerade auf YouTube gesehen, also ich habe es mir noch nicht angeschaut.
Aber könnte vielleicht interessant für dich sein.
Ich schau mir das auch noch bei Gelegenheit an 👍 

https://www.youtube.com/watch?v=h-9vhFeM3MY&t=5s&ab_channel=Amigoscode

**Comment by tridungng** [comment]
Heyho,

vielen Dank für die Teilung. Ganz zufälligerweise sah ich das Video heute auch in meinem Feed :) Ich hab mir das Video auch noch nicht angeschaut aber hab in Merkliste gespeichert ;)

Hier ist auch was Cooles: 
https://www.youtube.com/@ByteByteGo/featured

Der Autor dieses Kanals ist der Autor von den System Design Interview Buchserien. Daraus kann man jedenfalls einen besseren Überblick von IT-Systemen und Komponenten schaffen. Find ich sehr cool! :)

**Comment by WladimirHSJW** [comment]
💯
